kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
  name: fluentd
  namespace: ocp-log
  labels:
    component: fluentd
    logging-infra: fluentd
    provider: openshift
spec:
  selector:
    matchLabels:
      component: fluentd
      logging-infra: fluentd
      provider: openshift
  template:
    metadata:
      name: fluentd
      creationTimestamp: null
      labels:
        component: fluentd
        logging-infra: fluentd
        provider: openshift
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      serviceAccountName: logcollector
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
      securityContext: {}
      containers:
        - resources:
            limits:
              memory: 736Mi
            requests:
              cpu: 100m
              memory: 736Mi
          terminationMessagePath: /dev/termination-log
          name: fluentd
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: AWS_KEY_ID
              value: "xxxxxxxxxxxxxx"
            - name: AWS_SEC_KEY
              value: "xxxxxxxxxxxxxxx"
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - name: metrics
              containerPort: 24231
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: runlogjournal
              mountPath: /run/log/journal
            - name: varlog
              mountPath: /var/log
            - name: config
              readOnly: true
              mountPath: /fluentd/etc
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/ocp-log/fluentd:final
      serviceAccount: logcollector
      volumes:
        - name: runlogjournal
          hostPath:
            path: /run/log/journal
            type: ''
        - name: varlog
          hostPath:
            path: /var/log
            type: ''
        - name: config
          configMap:
            name: fluentd
            defaultMode: 420
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: ''
      dnsPolicy: ClusterFirst
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      priorityClassName: cluster-logging
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
