kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: fluentd-build
  namespace: ocp-log
  labels:
    name: fluentd-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'fluentd:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/fjcloud/fluentd-alpine-custom.git'
  triggers:
    - type: ConfigChange
  runPolicy: Serial
