kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-collector-privileged
  namespace: ocp-log
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged
