kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-collector-privileged-binding
  namespace: ocp-log
subjects:
  - kind: ServiceAccount
    name: logcollector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-collector-privileged
